### ISSUE TITLE
New license namespace request: ABST [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Angie3120** [spdx/license-namespace#3]
**1.** License Namespace: angiesbuyselltrade
**2.** Short identifier: ABST
 **3.** License Author or steward: Angela pugh
**4.** Description: Angie3120. Licensed namespaces
 **5.** Submitter name: Angela Pugh
 **6.** SPDX doc URL:  https://angiesbuyselltrade.com
 **7.** Submitter email: angelampugh18@gmail.com
 **8.** License list URL: https://angiesbuyselltrade.com
 **9.** Github repo URL: https://github.com/Angie3120/spdx-online-tools.git

**Comment by goneall** [comment]
The repo points to online tools, not a license repo
